### ISSUE TITLE
Add macOS Support

### ISSUE THREAD

**Issue by singhalrishi27** [lfroms/clouds#71]
CodeBase Won't Require Huge Changes to Bring it to Mac Since Its Written in SwiftUI

**Comment by lfroms** [comment]
Thanks for the suggestion. Clouds was designed to be mobile-first, meaning that much of its UI and UX was designed for use with a touch screen. In its current form, Clouds' design does not lend it self well to mouse input and the desktop, so porting to macOS is not trivial and would require designing a derivative of the UI with desktop-oriented appearance and layout.

There is no plan to build Clouds for macOS at this time.
